# Generated by Django 6.0 on 2026-01-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='purse_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
